### ISSUE TITLE
Can't find last release in a node.js repo

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/releasetool#1]
I'm trying to use releasetool to ship a new version of [nodejs-common](https://github.com/googleapis/nodejs-common/).  Generally we use the last tag with a `v*` to figure out the last release, but it looks like releasetool is having trouble figuring that out:

```sh
beckwith-macbookpro2:nodejs-common beckwith$ releasetool
o/ Hey, beckwith, let's release some stuff!
> Determining basic context.
GitHub Repo: JustinBeckwith/nodejs-common
> Figuring out the package name.
Looks like we're releasing nodejs-common.
> Figuring out what the last release was.
I couldn't figure out the last release for nodejs-common, so I'm assuming this is the first release. Can you tell me which git rev/sha to start the changelog at?
```

How is it trying to find the last release?

**Comment by theacodes** [comment]
We need to actually make a new command group for node.js. The current one is specific to Python. We should be able to re-use most of Python's logic.
