### ISSUE TITLE
Switch back to master after release

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/releasetool#11]
After running release tool, it left me in an autogenerated branch it used for the release:

```
releasetool (release-releasetool-0.1.1) $ 
```

After the release, it should return to the master branch, or which ever branch I was originally on.

**Comment by kinwa91** [comment]
I'm OK with it being in the branch, so I can review the changes etc..

**Comment by theacodes** [comment]
Yeah I'm thinking this is working as intended, @GoogleCloudPlatform/yoshi what do all ya'll think?

**Comment by tseaver** [comment]
FWIW, I have the following alias in my local `google-cloud-python` clone:

```
[alias]
	remaster = !"git checkout master && git fetch --all --prune && git merge upstream/master"
```

which I use probably a half-dozen or more times a day.

**Comment by JustinBeckwith** [comment]
SGTM :)
