### ISSUE TITLE
show change log for the release in PR comment

### ISSUE THREAD

**Issue by kinwa91** [GoogleCloudPlatform/releasetool#18]
Instead of showing a boring `This pull request was generated using releasetool.` message, let's instead show the change log for the latest release so reviewer better understand the release.

**Comment by JustinBeckwith** [comment]
@ofrobots was asking for this as well.

**Comment by theacodes** [comment]
How is this more helpful than putting in the commit delta? What if the changelog is edited?

**Comment by theacodes** [comment]
Gentle ping.

**Comment by JustinBeckwith** [comment]
It's just one less click. 🤷‍♂️ This isn't a huge deal, it's just a "nice to have".  I'm ok with the text in the PR desc not getting updated in the case of an edit.  Your call though :)

**Comment by theacodes** [comment]
I'm pretty concerned about having it in two locations, especially if we're prone to edits.

**Comment by kinwa91** [comment]
Not really a complaint, just a nice to have :)

**Comment by theacodes** [comment]
I'm gonna close for now, but let's see how things go. If y'all tell me it's that much more convenient and y'all don't do many edits, then I'm happy to do this.
