### ISSUE TITLE
[NodeJS] regenerate package-lock.json's

### ISSUE THREAD

**Issue by kinwa91** [GoogleCloudPlatform/releasetool#19]
We need to run

```
rm -rf node_modules package-lock.json samples/node_modules samples/package-lock.json && npm install && cd samples/ && npm link ../ && npm install && cd ../
```

to ensure package-lock.json are up to date.

**Comment by theacodes** [comment]
Is this still relevant? Didn't we get rid of lock files?

**Comment by JustinBeckwith** [comment]
Yup, not relevant.  Kill all lock files.

**Comment by hdp617** [comment]
Could we have regenerating package-lock.json as an option? We need to use them for Node.js Functions Framework?

**Comment by JustinBeckwith** [comment]
What specifically are you trying to do?  Lock files aren't relevant for released npm modules, so for releases it really shouldn't matter.  It's only relevant to a release when you have something that relies on `npm link` for running tests (like we have here with samples).  

If you're just looking to periodically update your `package-lock.json`, there is a great setting for this in renovate:
https://github.com/google/gts/blob/master/renovate.json

**Comment by hdp617** [comment]
I _think_ `package-lock.json` is used in function-to-app conversion to speed up builds. 
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/converter/generate-package-lock
