### ISSUE TITLE
Add link to commit

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/releasetool#38]
Today when the release log is generated, it doesn't include a reference to the commit that led to the change.  For example:
https://github.com/googleapis/nodejs-promisify/blob/master/CHANGELOG.md

It would be nice if we could include the commit like this:
https://github.com/googleapis/nodejs-common/releases/tag/v0.19.2

**Comment by tseaver** [comment]
Adding the commit hash seems redundant to the PR reference to me.

**Comment by JustinBeckwith** [comment]
It shows the PR reference when it's in the release notes.  The problem is that it *doesn't* show it in the changelog:
https://github.com/googleapis/nodejs-promisify/blob/master/CHANGELOG.md

I'd be open to using the full link to the PR as well 🤷‍♂️

**Comment by JustinBeckwith** [comment]
FYI @ofrobots
