### ISSUE TITLE
Node.js not supported?

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/releasetool#7]
I decided to give this a shot, to help me release a library.

* Installation: Even for someone who doesn't grok Python, the installation instructions worked flawlessly on my mac 🎉.
* `releasetool start`:

```sh
❯ releasetool start
Which language (python, python-tool)?: nodejs
Error: invalid choice: nodejs. (choose from python, python-tool)
```

Do I need the master branch, etc. for Node.js support?

**Comment by kinwa91** [comment]
Yeah I installed from head to get nodejs support:

```
$  git clone https://github.com/GoogleCloudPlatform/releasetool
$  cd releasetool && pip install -e .

**Comment by theacodes** [comment]
Done: https://pypi.org/project/gcp-releasetool/0.2.0/

The "tag" command probably doesn't work right yet. Please let me know when y'all give it a shot.
